[tox]
envlist = py310, py311, py312, py313
skip_missing_interpreters = true

[testenv]
package = wheel
wheel_build_env = .pkg
allowlist_externals = uv

# install dependencies via uv rather than pip so we mirror dev environment
deps =
commands =
    uv sync --group dev
    uv run pytest