# SDK identity
SDK_VERSION = "wildedge-python-0.1.0"
PROTOCOL_VERSION = "1.0"

# Env vars
ENV_DSN = "WILDEDGE_DSN"
ENV_DEBUG = "WILDEDGE_DEBUG"

# Defaults
DEFAULT_MAX_QUEUE_SIZE = 200
DEFAULT_BATCH_SIZE = 10
DEFAULT_FLUSH_INTERVAL_SEC = 60.0
DEFAULT_HTTP_TIMEOUT = 15.0

# Consumer backoff
BACKOFF_MIN = 1.0
BACKOFF_MAX = 60.0
BACKOFF_MULTIPLIER = 2.0
IDLE_POLL_INTERVAL = 5.0

# Error message truncation
ERROR_MSG_MAX_LEN = 200

# Device ID persistence
BATCH_SIZE_MIN = 1
BATCH_SIZE_MAX = 100
FLUSH_INTERVAL_MIN = 1
FLUSH_INTERVAL_MAX = 3600
MAX_QUEUE_SIZE_MIN = 10
MAX_QUEUE_SIZE_MAX = 10000
